version: '3'
services:
  zookeeper-pinot:
    image: zookeeper:3.6.1
    container_name: zookeeper-pinot
    hostname: zookeeper-pinot
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    volumes:
      - ${HOME}/volumes/pinot/zookeeper/data:/data
      - ${HOME}/volumes/pinot/zookeeper/datalog:/datalog
  pinot-controller:
    image: apachepinot/pinot
    container_name: pinot-controller
    hostname: pinot-controller
    volumes:
      - ${HOME}/volumes/pinot/controller/data:/opt/data
      - ${HOME}/volumes/pinot/samples:/opt/pinot/samples
    ports:
      - "9000:9000"
    command: StartController -zkAddress zookeeper-pinot:2181
    depends_on:
      - zookeeper-pinot
  pinot-broker:
    image: apachepinot/pinot
    container_name: pinot-broker
    hostname: pinot-broker
    ports:
      - "8099:8099"
    command: StartBroker -zkAddress zookeeper-pinot:2181
    depends_on:
      - pinot-controller
  pinot-server:
    image: apachepinot/pinot
    container_name: pinot-server
    hostname: pinot-server
    volumes:
      - ${HOME}/volumes/pinot/server/data:/opt/data
      - ${HOME}/volumes/pinot/server/segments:/opt/segments
    ports:
      - "8098:8098"
    command: StartServer -zkAddress zookeeper-pinot:2181 -dataDir /opt/data -segmentDir /opt/segments
    depends_on:
      - pinot-controller

networks:
  default:
    external:
      name: sandbox
